### ISSUE TITLE
[Question] Why does the leaflet itself calls only one tile by the CreateTile overloading function?

### ISSUE THREAD

**Issue by JeongJun-Lee** [0nza1101/leaflet-tilelayer-mbtiles-ts#1]
![image](https://user-images.githubusercontent.com/11474775/62288877-c83b9780-b476-11e9-8268-d041212ee751.png)

Hello author, 
Thank you for your nice Node module again.

But, I often meet the problem like attached screenshot when loading map. Actually 6 tiles is need for the one screen to be shown normally. But only one tile is shown like attached screenshot. I think the problem is not from your node module, because the reason why only one tile is shown on the screen is the leaflet(v1.5.0) itself calls only one tile by the CreateTile overloading function. This situation is not always happened 100%. 
Do you have any idea?

Thanks,
JJ

**Comment by 0nza1101** [comment]
Hello,

Sorry for the late reply. Can you provide me your sample or can you make sure your .mbtiles is properly formatted using this [mbtiles spec](https://github.com/mapbox/mbtiles-spec/blob/master/1.1/spec.md) you can open your file with https://sqlitebrowser.org/ to your file structure.
